# Generated by Django 4.2.1 on 2025-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='forget_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
