# Generated by Django 5.2 on 2025-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0008_remove_users_user_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Employ',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
