# Generated by Django 5.0.6 on 2025-05-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0004_profile_profile_pic_alter_profile_forget_token'),
        ('HomeServices_app', '0010_alter_users_profile_pic'),
    ]

    operations = [
    ]
