# Generated by Django 5.0.6 on 2025-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0011_merge_20250506_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='forget_token',
            field=models.CharField(max_length=1000),
        ),
    ]
